---
title: "Exam2Stats"
author: "Elise Haylett"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Useful vectors

```{r}
(6125, 6995, 7499, 5995, 6250, 6499, 7995, 6995, 7500, 7000)
(150, 147, 136, 134, 130, 134, 134, 128, 136, 158)
(201, 220, 192, 146, 182, 172, 303, 180, 192, 206)
```



## Chapter 20

```{r chapter 20}
########################
# CI for single mean mu#
########################

myData <- c(6125, 6995, 7499, 5995, 6250, 6499, 7995, 6995, 7500, 7000)

n <- length(myData)

df <- n - 1

ybar <- mean(myData)
s <- sd(myData)

CIlev <- .95

alpha <- 1-CIlev
alphaovertwo <- alpha/2
oneminusalphaovertwo <- 1- alpha/2
tinCI <- qt(oneminusalphaovertwo,df)

tinCI #t in a CI formula

LowMu <- ybar - tinCI * s/sqrt(n)
UpMu <- ybar + tinCI * s/sqrt(n)

CI <- c(LowMu,UpMu)

cat("The ", CIlev*100, " % confidence interval for mu is", CI) #concatenate

```

## Chapter 22 Proportions

```{r chapter 22 proportions}
# TWO PROPORTIONS
# SECTION 1:  DATA ARE SUMMARIZED AS PROPORTION OF SUCCESSES PER SAMPLE.
# phat = proportion of successes.   n = sample size.  
phat <- c(.8, .48)
n <- c(176,176)
# CONFIDENCE INTERVAL FOR p1 - p2.
conf.level <- 0.95
pdiff <- phat[1] - phat[2]
pdiff
#standard error
se.pdiff <- sqrt(sum(phat*(1-phat)/n))
se.pdiff
zstar <- qnorm((1 + conf.level)/2)
zstar
#####
lcl <- pdiff - zstar*se.pdiff
ucl <- pdiff + zstar*se.pdiff
#####
CI <- c(lcl,ucl)
CI
#concatenate
cat("The", conf.level*100, "% confidence interval for p1 - p2 mu is", CI) 
```

## Chapter 22 Means

```{r chapter 22 means}
#########################################
#Ch 22: Comparing two independent means #
#########################################

######
# HT #
######

ybar1 <- 73.26
s1 <- 4.97
n1 <- 31

ybar2 <- 77.78
s2 <- 3.7
n2 <- 30

df <- (s1^2/n1 + s2^2/n2)^2/(1/(n1 - 1)*(s1^2/n1)^2 + 1/(n2 - 1)*(s2^2/n2)^2)

df

tstat <- (ybar1 - ybar2)/sqrt(s1^2/n1 + s2^2/n2)

cat("The t-stat is",tstat)

#less
LT <- pt(tstat,df)

#more
GT <- 1 - pt(tstat,df)

#tails
Tail <- 2*min(LT,GT)

cat("P-value will be")
list(LessThan = LT, GreaterThan = GT, TailArea = Tail)
```

## Chapter 23

```{r chapter 23}
# Ch 23: Paired Data

# We examine how paired data can be examined.  Paired data refers to cases where the two different
# Samples are not indepdendent of each other.

# Example from book.  An insurance agent compared prices for car insurance for 10 clients using
# diff2 carriers versus a diff1 carrier.  Thequestion of interest is whether diff2 carriers
# offer cheaper coverage on average, and if so, how much.

dry <- c(150, 147, 136, 134, 130, 134, 134, 128, 136, 158)
wet <- c(201, 220, 192, 146, 182, 172, 303, 180, 192, 206)
diff <- dry - wet

hist(diff)

# CI for mu_difference.
mean(diff)
sd(diff)
conf.level <- 0.95
n <- length(diff)
df <- n - 1
tstar <- qt((1+conf.level)/2, df)

LCL <- mean(diff) - tstar*sd(diff)/sqrt(n)
UCL <- mean(diff) + tstar*sd(diff)/sqrt(n)

CI <- c(LCL, UCL)

cat("The ", conf.level*100, " % confidence interval for mu_difference is", CI) #concatenate
```

## Chapter 24

```{r chapter 24}
############################################
# Test 3
# Independence = two variables Ho: no association between row and column
############################################


restaurant <- matrix(c(42, 84, 19, 55), ncol = 2, byrow = TRUE)
colnames(restaurant) <- c("soup", "no soup")
rownames(restaurant) <- c("sandwich", "no sandwich")

obstable <- as.table(restaurant)
obstable

chisq.test(obstable)

ChiSq <- chisq.test(as.table(obstable), correct = FALSE)
ChiSq

names(ChiSq)

ChiSq$observed
ChiSq$expected
ChiSq$residuals
ChiSq$stdres
ChiSq$p.value
ChiSq$stat

sum(ChiSq$residuals^2) #same as the stat
```